#' Summarize transition probabilities
#'
#' @description
#' Returns a data frame.
#'
#' @param probs Data frame with transition probabilities, as generated by 'dtms_transitions'
#' @param fromvar Variable with starting state, optional.
#' @param tovar Variable with receiving state, optional.
#' @param timevar Variable with time scale, optional.
#' @param probvar Variable with probabilities, optional.
#' @param digits Number of digits to show, default is 6.
#' @param format Show results in decimal format or percentage, default is decimal.
#' @param sep Separator for long state names, default is '_'
#'
#' @return A data frame
#' @export
#'
#' @examples
#' simple <- dtms(transient=c("A","B"),
#'                absorbing="X",
#'                timescale=0:20)
#' estdata <- dtms_format(data=simpledata,
#'                        dtms=simple,
#'                        idvar="id",
#'                        timevar="time",
#'                        statevar="state")
#' estdata <- dtms_clean(data=estdata,
#'                       dtms=simple)
#' fit <- dtms_fit(data=estdata)
#' probs    <- dtms_transitions(dtms=simple,
#'                              model = fit)
#' summary(probs)

dtms_probs_summary <- function(probs,
                               fromvar="from",
                               tovar="to",
                               timevar="time",
                               probvar="P",
                               sep="_",
                               digits=4,
                               format="decimal") {

  # Get short state names
  probs[,fromvar] <- dtms_getstate(probs[,fromvar],sep=sep)
  probs[,tovar] <- dtms_getstate(probs[,tovar],sep=sep)

  # Aggregate (starting from minimum)
  result <- stats::aggregate(P~from+to,data=probs,FUN=min)
  names(result)[3] <- "MIN"

  # Add time values
  result$MINtime <- probs[match(result$MIN,probs[,probvar]),timevar]

  # Add max
  result$MAX <- stats::aggregate(P~from+to,data=probs,FUN=max)[,probvar]
  result$MAXtime <- probs[match(result$MAX,probs[,probvar]),timevar]

  # Add other statistics
  result$MEDIAN <- stats::aggregate(P~from+to,data=probs,FUN=stats::median)[,probvar]
  result$MEAN <- stats::aggregate(P~from+to,data=probs,FUN=mean)[,probvar]

  # Order result
  ordering <- order(result[,fromvar],result[,tovar])
  result <- result[ordering,]

  # Rounding
  result[,c("MIN","MAX","MEDIAN","MEAN")] <-
    round(result[,c("MIN","MAX","MEDIAN","MEAN")],digits=digits)

  # For printing
  if(format=="percent") {
    result[,c("MIN","MAX","MEDIAN","MEAN")] <-
      result[,c("MIN","MAX","MEDIAN","MEAN")]*100
  }

  # Return
  return(result)

}
